#!/usr/bin/env bash

tempfile=`mktemp -u /tmp/ipfetch.XXXXXX`
IP=""

usage() {
	cat <<- _end_of_usage  
	Usage: ipfetch [OPTIONS]...
	Neofetch like tool that can lookup IPs.
	Options:
	    -h          print this text and exit
	    -ip <IP>    ip address to fetch (fetches own ip by default)

	_end_of_usage
}

error() {
	echo "$1" && exit 1
}

parse_args() {
	# if no arguments passed, use current ip
	[ $# -eq 0 ] && return 0
	
	while [ $# -ne 0 ]
	do
		case "$1" in
			"-h")  usage && exit 0 ;;
			"-ip") IP=$2 && shift ;;
			*) error "Unknown argument $1!" ;;
		esac
		shift >/dev/null 2>&1
	done
}

ipfetch() {
	if [ ! -x "$(command -v jq)" ]; then
  		echo 'Note: jq looks like not installed. to run ipfetch, jq needs to be installed.' >&2
  		exit 1
	fi
	
	# if no ip is passed, the IP variable is empty, so the api link will work as expected
	wget https://ip.seeip.org/geoip/$IP -O "$tempfile" >/dev/null 2>&1 || error "IP is invalid or API is down!"

	# delete backslashes
	sed -i 's/\\//g' "$tempfile"

	local ip=`jq -r '.ip' "$tempfile"`
	local country=`jq -r '.country' "$tempfile"`
	local timezone=`jq -r '.timezone' "$tempfile"`
	local latitude=`jq -r '.latitude' "$tempfile"`
	local longitude=`jq -r '.longitude' "$tempfile"`
	local asn=`jq -r '.asn' "$tempfile"`

	# Using sed to remove underscores in order to get cleaner output
	# I will make this far more efficent in the next update
	sed -i 's/_/ /g' "$tempfile"

	local continent=`jq -r '."continent code"' "$tempfile"`
	local city=`jq -r '.city' "$tempfile"`
	local isp=`jq -r '.organization' "$tempfile"`
	local region=`jq -r '.region' "$tempfile"`

	local flag=`echo "$country" | sed -r 's/ /_/g'`

	rm "$tempfile"

	# All of those \033 you see are cursor positions.
	#Here is a good tutorial for it: https://thoughtsordiscoveries.wordpress.com/2017/04/26/set-and-read-cursor-position-in-terminal-windows-and-linux/
	
	echo -e "\n`cat /usr/share/ipfetch/$flag`\
		\033[9D\033[s \033[9A Ip: $ip\
		\033[u\033[8A  Continent: $continent\
		\033[u\033[7A  Country: $country\
		\033[u\033[6A  Region: $region\
		\033[u\033[5A  City: $city\
		\033[u\033[4A  ISP: $isp\
		\033[u\033[3A  Timezone: $timezone\
		\033[u\033[2A  Latitude: $latitude\
		\033[u\033[1A  Longitude: $longitude\
		\033[u  ASN: $asn\
		\033[u \033[10A -------------------- \
		\033[u \n"
}

parse_args "$@"
ipfetch
