#!/bin/bash
tempfile=`mktemp -u /tmp/ipfetch.XXXXXX`

if [ $1 == "-ip" ] >/dev/null 2>&1 ; then
	wget https://ip.seeip.org/geoip/$2 -O tempfile >/dev/null 2>&1 || exit 1
fi

# If no arguments were passed it will default to your own ip
[ "$1" == "" ] >/dev/null 2>&1 && wget https://ip.seeip.org/geoip/ -O tempfile >/dev/null 2>&1

# Replacing spaces with underscores
sed -i 's/ /_/g' tempfile
sed -i 's/\\//g' tempfile

# Using grep to extract json data
ip=`grep -o '"ip":"[^"]*' tempfile | grep -o '[^"]*$'`
continent=`grep -o '"continent_code":"[^"]*' tempfile | grep -o '[^"]*$'`
city=`grep -o '"city":"[^"]*' tempfile | grep -o '[^"]*$'`
isp=`grep -o '"organization":"[^"]*' tempfile | grep -o '[^"]*$'`
country=`grep -o '"country":"[^"]*' tempfile | grep -o '[^"]*$'`
timezone=`grep -o '"timezone":"[^"]*' tempfile | grep -o '[^"]*$'`
latitude=`python3 -c "import sys, json; file=open('tempfile'); dr=file.read(); data=json.loads(dr); print(data['latitude'])"` >/dev/null 2>&1
longitude=`python3 -c "import sys, json; file=open('tempfile'); dr=file.read(); data=json.loads(dr); print(data['longitude'])"` >/dev/null 2>&1
asn=`python3 -c "import sys, json; file=open('tempfile'); dr=file.read(); data=json.loads(dr); print(data['asn'])"` >/dev/null 2>&1
region=`grep -o '"region":"[^"]*' tempfile | grep -o '[^"]*$'`

rm tempfile

# All of those \033 you see are cursor positions. Here is a good tutorial for it: 
# https://thoughtsordiscoveries.wordpress.com/2017/04/26/set-and-read-cursor-position-in-terminal-windows-and-linux/
echo -e "\n`cat /usr/share/ipfetch/$country`\033[s \033[9A Ip: $ip\033[u\033[8A  Continent: $continent\033[u\033[7A  Country: $country\033[u\033[6A  Region: $region\033[u\033[5A  City: $city\033[u\033[4A  ISP: $isp\033[u\033[3A  Timezone: $timezone\033[u\033[2A  Latitude: $latitude\033[u\033[1A  Longitude: $longitude\033[u  ASN: $asn \033[u \033[10A -------------------- \033[u \n"
